release-1.0-documentation
EdgeNet-project/edgenet-legacy-2024 pull request #118
Opened 2020-06-24 15:28 UTC by timur-friedman

2020-06-24 15:30 UTC, timur-friedman commented
I've added comments to the main README encouraging new users to write unit tests and I've also added an architecture document README with links to the source files.

One thing that I couldn't figure out how to do is to put the correct branch in the URL when referring to another document in the GitHub directory tree. I explicitly put the name of the current branch in the URL, but this seems to not be the correct way to do things.

2020-07-01 10:25 UTC, bsenel requested changes
Timur, I pointed out some changes to make. Can you please check them out?

2020-07-01 10:25 UTC, bsenel commented on docs/architecture/README.md
> +Using namespaces and resource quotas is a perfectly classic approach to handling Kubernetes multitenancy, and so is EdgeNet’s adoption of a hierarchical naming convention for the namespaces. Currentl
EdgeNet users run the applications in the namespaces that follows two schemas as `authority-<authority-name>-team-<team-name>-slice-<slice-name>` and `authority-<authority-name>-slice-<slice-name>`. In my opinion, we should update this part, what do you think?

2020-07-01 10:25 UTC, bsenel commented on docs/architecture/README.md
> +Resource quotas are associated with authorities, which can then share them out amongst teams, and teams amongst slices.
Total resource quotas are associated with authorities, which can then be shared amongst slices. In the next iterations, the total resource quota per team will be enabled to prevent over-creation of slices in teams. Resource quotas are associated with authorities and teams to make application deployment forbidden, and with slices to limit resource consumption.

2020-07-01 10:25 UTC, bsenel commented on docs/architecture/README.md
> +Users access rights to resources are handled… (here or elsewhere?)
Users access rights to resources are handled by [RBAC](https://kubernetes.io/docs/reference/access-authn-authz/rbac/). Roles and role bindings are automatically created based on the type of user which can be an authority admin or normal user. Authority, Team, and Slice controllers use RBAC to create roles and role bindings for permission control.  Authority managers can also create their own roles and role bindings under the control of [OPA](https://www.openpolicyagent.org/).

2021-04-15 08:16 UTC, bsenel approved these changes

2021-04-15 08:17 UTC, merged