Release 1.0 unit testing
EdgeNet-project/edgenet-legacy-2024 pull request #119
Opened 2020-07-02 11:21 UTC by eqfarhad

Implemented Unit Test for the user custom resource

2020-07-03 09:58 UTC, bsenel requested changes
You did a good job, so, it is OK in general! 👍  But, there are some parts to be fixed. Please look at my reviews.

Would you be so kind as to pass Kubernetes client and EdgeNet client into the functions as very first parameters in all packages? Moreover, you should remove all the fmt.print related parts you added.

By the way, I really want you to just focus on your parts rather than playing with the code that works. If you see a part that should be updated, please contact me first to discuss it.

2020-07-03 09:58 UTC, bsenel commented on cmd/nodecontribution/main.go
> +func main(kubernetes kubernetes.Interface, edgenet versioned.Interface) {
How will you pass these parameters? This is not the correct approach.

2020-07-03 09:58 UTC, bsenel commented on cmd/nodecontribution/main.go
> -	authorization.SetKubeConfig()
If you remove this part, in which way you prepare the kubeconfig file for the clients?

2020-07-03 09:58 UTC, bsenel commented on cmd/nodecontribution/main.go
> +	clientset := kubernetes
Please look at the example [here](https://github.com/EdgeNet-project/edgenet/blob/release-1.0-unit-testing/cmd/authority/main.go).

2020-07-03 09:58 UTC, bsenel commented on cmd/slice/main.go
> +func main(clientset kubernetes.Interface, edgenetClientset versioned.Interface) {
The same issue?

2020-07-03 09:58 UTC, bsenel commented on cmd/team/main.go
> +func main(clientset kubernetes.Interface, edgenetClientset versioned.Interface) {
The same issue?

2020-07-03 09:58 UTC, bsenel commented on cmd/user/main.go
> +func main(clientset kubernetes.Interface, edgenetClientset versioned.Interface) {
The same issue?

2020-07-03 09:58 UTC, bsenel commented on pkg/controller/v1/nodelabeler/handler.go
> +	Init(kubernetes kubernetes.Interface, edgenet versioned.Interface) error
Why does **Init** return an error?

2020-07-03 09:58 UTC, bsenel commented on pkg/controller/v1/nodelabeler/handler.go
>  	return nil
Reason?

2020-07-03 09:58 UTC, bsenel commented on pkg/node/node.go
> +func GetGeolocationByIP(hostname string, ipStr string, clientset kubernetes.Interface) (bool, map[string]string) {
What is the purpose of returning this map since geolabels are attached to nodes, in this function?

2020-07-03 09:58 UTC, bsenel commented on pkg/node/node.go
> +	result := setNodeLabels(hostname, geoLabels, clientset)
This is the line geolabels get consumed.

2020-07-03 09:58 UTC, bsenel commented on pkg/node/node.go
> +	return result, geoLabels
Is it necessary?

2020-07-03 09:58 UTC, bsenel commented on pkg/controller/v1alpha/authority/authority_test.go
> +	status, err := g.edgenetclient.AppsV1alpha().Users(fmt.Sprintf("authority-%s", g.authorityObj.GetName())).List(metav1.ListOptions{})
Is it necessary?

2020-07-03 09:58 UTC, bsenel commented on pkg/controller/v1alpha/authority/handler.go
> -			"pods":                          resource.Quantity{Format: "0"},
Can you please let me know the reference study or information made you change this part? And can you please look at resource quantity [documentation](https://godoc.org/k8s.io/apimachinery/pkg/api/resource#Quantity) and [code](https://sourcegraph.com/github.com/kubernetes/apimachinery/-/blob/pkg/api/resource/quantity_example_test.go)?

2020-07-03 09:58 UTC, bsenel commented on pkg/controller/v1alpha/nodecontribution/controller.go
> -			for key, _ := range nodeObj.Labels {
I would prefer having the value part as underscore.

2020-07-03 09:58 UTC, bsenel commented on pkg/controller/v1alpha/team/handler.go
> -			"pods":                          resource.Quantity{Format: "0"},
I would prefer to keep explicit definitions.

2020-07-03 09:58 UTC, bsenel commented on pkg/controller/v1alpha/user/controller_test.go
> +	authorityHandler.ObjectCreated(g.authorityObj.DeepCopy())
ObjectCreated() function is called when an object is created. You should put line 19 before line 18.

2020-07-03 09:58 UTC, bsenel commented on pkg/controller/v1alpha/user/controller_test.go
> +		t.Error("Add func of event handler authority doesn't work properly")
You test the User Custom Resource. Is it necessary?

2020-07-03 09:58 UTC, bsenel commented on pkg/controller/v1alpha/user/handler.go
> +	log.Info("\nUserHandler.ObjectCreated\n")
Is it necessary?

2020-07-03 09:58 UTC, bsenel commented on pkg/controller/v1alpha/user/handler.go
> +			_, err = registration.CreateServiceAccount(userCopy, "main", t.clientset, true)
What is the purpose of having a boolean of true as the last parameter?

2020-07-03 09:58 UTC, bsenel commented on pkg/controller/v1alpha/user/handler.go
> +func (t *Handler) setEmailVerification(userCopy *apps_v1alpha.User, authorityName string) string {
Why do you return a string instead of return an error?

2020-07-03 09:58 UTC, bsenel commented on pkg/controller/v1alpha/user/handler.go
> +func (t *Handler) createAUPRoleBinding(userCopy *apps_v1alpha.User) string {
Why do you return a string instead of an error?

2020-07-03 09:58 UTC, bsenel commented on pkg/node/node.go
> +	var err error
You don't need to add that here. `_, err := clientset.CoreV1().Nodes().Patch(hostname, types.JSONPatchType, nodesJSON)` should also work.

2020-07-03 09:58 UTC, bsenel commented on pkg/node/node.go
> +func GetGeolocationByIP(hostname string, ipStr string, clientset kubernetes.Interface) (bool, map[string]string) {
Why do you return a map?

2020-07-03 09:58 UTC, bsenel commented on pkg/registration/registration.go
> +func CreateServiceAccount(userCopy *apps_v1alpha.User, accountType string, clientset kubernetes.Interface, returnerror bool) (*corev1.ServiceAccount, error) {
returnerror bool?

2020-07-03 09:58 UTC, bsenel commented on pkg/registration/registration.go
> +	} */
You should remove this part.

2020-07-03 09:58 UTC, bsenel commented on pkg/controller/v1alpha/user/user_test.go
> +		user, _ := g.edgenetclient.AppsV1alpha().Users(fmt.Sprintf("authority-%s", g.authorityObj.GetName())).Get(g.userObj.GetName(), metav1.GetOptions{})
It doesn't test any functionality developed by EdgeNet here but the fake client. You should include the changes triggered by ObjectCreated().

2020-07-03 09:58 UTC, bsenel commented on pkg/controller/v1alpha/user/user_test.go
> +	t.Run("Check service error", func(t *testing.T) {
Can you please explain what do you think of this part?

2020-07-03 09:58 UTC, bsenel commented on pkg/controller/v1alpha/user/user_test.go
> +		g.edgenetclient.AppsV1alpha().Users(fmt.Sprintf("authority-%s", g.authorityObj.GetName())).Create(g.userObj.DeepCopy())
Please invoke ObjectCreated() function following an object creation.

2020-07-03 09:58 UTC, bsenel commented on pkg/controller/v1alpha/user/user_test.go
> +		g.edgenetclient.AppsV1alpha().Users(fmt.Sprintf("authority-%s", g.authorityObj.GetName())).Create(g.userObj.DeepCopy())
Same as above.

2020-07-03 09:58 UTC, bsenel commented on pkg/controller/v1alpha/user/user_test.go
> +		g.edgenetclient.AppsV1alpha().Users(fmt.Sprintf("authority-%s", g.authorityObj.GetName())).Create(g.userObj.DeepCopy())
Same as above.

2020-07-03 09:58 UTC, bsenel commented on pkg/controller/v1alpha/user/user_test.go
> +	roleBindings, _ := g.handler.clientset.RbacV1().RoleBindings(user.GetNamespace()).List(roleBindingListOptions)
Please include the other role bindings created.

2020-07-03 09:58 UTC, bsenel commented on pkg/controller/v1alpha/user/user_test.go
> +	roleBindingListOptions = metav1.ListOptions{FieldSelector: fmt.Sprintf("metadata.name!=%s-user-aup-%s", user.GetNamespace(), user.GetName())}
Same as above.

2020-07-03 09:58 UTC, bsenel commented on pkg/controller/v1alpha/user/user_test.go
> +	roleBindings, _ := g.handler.clientset.RbacV1().RoleBindings(user.GetNamespace()).List(roleBindingListOptions)
I mean doing this one by one according to their names.

2020-07-03 09:58 UTC, bsenel commented on pkg/controller/v1alpha/user/user_test.go
> +		time.Sleep(1 * time.Second)
Doesn't millisecond work?

2020-07-03 09:58 UTC, bsenel commented on pkg/node/node_test.go
> +		{clientset: testclient.NewSimpleClientset(&corev1.Node{
You may consider having a test group in this unit testing file as well.

2020-07-03 10:37 UTC, eqfarhad commented on pkg/node/node_test.go
> +		{clientset: testclient.NewSimpleClientset(&corev1.Node{
True, This unit test file was created by M1 students and just I just improved it based on their structure, so we can change their codes and use test group as well

2020-07-03 10:45 UTC, eqfarhad commented on pkg/controller/v1alpha/user/user_test.go
> +		time.Sleep(1 * time.Second)
Yes, It's working with millisecond and even microsecond. 
so i'm going to change it to micro.

2020-07-03 16:56 UTC, bsenel commented on pkg/controller/v1alpha/user/user_test.go
> +	authorityRequestObj apps_v1alpha.AuthorityRequest
It is not in use in this unit testing file.

2020-07-06 07:41 UTC, eqfarhad commented on pkg/controller/v1alpha/user/user_test.go
> +	authorityRequestObj apps_v1alpha.AuthorityRequest
Fixed

2020-07-06 08:40 UTC, eqfarhad commented on pkg/controller/v1/nodelabeler/handler.go
> +	Init(kubernetes kubernetes.Interface, edgenet versioned.Interface) error
actually no reason and i was wondering why too :D
before any changes, the init function was still returning an error while nothing was happening in it so i just kept it.
btw now get fixed.

2020-07-06 08:41 UTC, eqfarhad commented on pkg/controller/v1/nodelabeler/handler.go
>  	return nil
Removed and Fixed

2020-07-06 08:41 UTC, eqfarhad commented on cmd/user/main.go
> +func main(clientset kubernetes.Interface, edgenetClientset versioned.Interface) {
True, Fixed

2020-07-06 08:42 UTC, eqfarhad commented on cmd/team/main.go
> +func main(clientset kubernetes.Interface, edgenetClientset versioned.Interface) {
Yes, Fixed

2020-07-06 08:42 UTC, eqfarhad commented on cmd/slice/main.go
> +func main(clientset kubernetes.Interface, edgenetClientset versioned.Interface) {
Changed

2020-07-06 08:42 UTC, eqfarhad commented on cmd/nodecontribution/main.go
> +	clientset := kubernetes
thank you, fixed

2020-07-06 08:43 UTC, eqfarhad commented on cmd/nodecontribution/main.go
> +func main(kubernetes kubernetes.Interface, edgenet versioned.Interface) {
you are completely right, I changed it

2020-07-06 08:44 UTC, eqfarhad commented on pkg/node/node.go
> +func GetGeolocationByIP(hostname string, ipStr string, clientset kubernetes.Interface) (bool, map[string]string) {
I didn't know about the fact that they are getting attached to nodes
Fixed

2020-07-06 09:25 UTC, eqfarhad commented on pkg/controller/v1alpha/authority/authority_test.go
> +	status, err := g.edgenetclient.AppsV1alpha().Users(fmt.Sprintf("authority-%s", g.authorityObj.GetName())).List(metav1.ListOptions{})
No it is not, I've added to have extra info about that part.
now removed it.

2020-07-06 09:29 UTC, eqfarhad commented on pkg/controller/v1alpha/authority/handler.go
> -			"pods":                          resource.Quantity{Format: "0"},
Sure, I'm going to read the document.

The vs was keeping show me warnings regarding this part.
and as solution it was recommending me to remove this part

changed it again to complete definition

2020-07-06 09:29 UTC, eqfarhad commented on pkg/controller/v1alpha/nodecontribution/controller.go
> -			for key, _ := range nodeObj.Labels {
Sure, It makes sense

2020-07-06 09:34 UTC, eqfarhad commented on pkg/controller/v1alpha/team/handler.go
> -			"pods":                          resource.Quantity{Format: "0"},
Fixed

2020-07-06 09:39 UTC, eqfarhad commented on pkg/controller/v1alpha/user/controller_test.go
> +		t.Error("Add func of event handler authority doesn't work properly")
It's not necessary but thought it might act as double check :)
-removed this part

2020-07-06 09:40 UTC, eqfarhad commented on pkg/controller/v1alpha/user/handler.go
> +	log.Info("\nUserHandler.ObjectCreated\n")
Nope, I was using it for having more information and debugging 😃 
-removed

2020-07-06 09:51 UTC, eqfarhad commented on pkg/controller/v1alpha/user/handler.go
> +			_, err = registration.CreateServiceAccount(userCopy, "main", t.clientset, true)
I wanted to get error from this part, so by passing this extra field, i'm sure it's going to return me an error.
-removed this customization and gonna use another way to make an error happen

2020-07-06 10:05 UTC, eqfarhad commented on pkg/controller/v1alpha/user/handler.go
> +func (t *Handler) setEmailVerification(userCopy *apps_v1alpha.User, authorityName string) string {
True, 
-changed it to error

2020-07-06 10:08 UTC, eqfarhad commented on pkg/controller/v1alpha/user/handler.go
> +func (t *Handler) createAUPRoleBinding(userCopy *apps_v1alpha.User) string {
-Fixed

2020-07-06 10:10 UTC, eqfarhad commented on pkg/node/node.go
> +	var err error
-Fixed

2020-07-06 10:10 UTC, eqfarhad commented on pkg/node/node.go
> +func GetGeolocationByIP(hostname string, ipStr string, clientset kubernetes.Interface) (bool, map[string]string) {
-Fixed

2020-07-06 10:12 UTC, eqfarhad commented on pkg/registration/registration.go
> +func CreateServiceAccount(userCopy *apps_v1alpha.User, accountType string, clientset kubernetes.Interface, returnerror bool) (*corev1.ServiceAccount, error) {
-Fixed

2020-07-06 10:12 UTC, eqfarhad commented on pkg/registration/registration.go
> +	} */
Sure

2020-07-06 12:52 UTC, eqfarhad commented on pkg/controller/v1alpha/user/user_test.go
> +		user, _ := g.edgenetclient.AppsV1alpha().Users(fmt.Sprintf("authority-%s", g.authorityObj.GetName())).Get(g.userObj.GetName(), metav1.GetOptions{})
True, I Improved it

2020-07-06 13:36 UTC, eqfarhad commented on pkg/controller/v1alpha/user/user_test.go
> +	t.Run("Check service error", func(t *testing.T) {
Tried to delete the created user before doing the next test but as i checked it doesn't have any effect
-removed it

2020-07-06 13:36 UTC, eqfarhad commented on pkg/controller/v1alpha/user/user_test.go
> +		g.edgenetclient.AppsV1alpha().Users(fmt.Sprintf("authority-%s", g.authorityObj.GetName())).Create(g.userObj.DeepCopy())
-done

2020-07-06 13:37 UTC, eqfarhad commented on pkg/controller/v1alpha/user/user_test.go
> +		g.edgenetclient.AppsV1alpha().Users(fmt.Sprintf("authority-%s", g.authorityObj.GetName())).Create(g.userObj.DeepCopy())
-fixed

2020-07-06 13:37 UTC, eqfarhad commented on pkg/controller/v1alpha/user/user_test.go
> +		g.edgenetclient.AppsV1alpha().Users(fmt.Sprintf("authority-%s", g.authorityObj.GetName())).Create(g.userObj.DeepCopy())
-fixed

2020-07-06 14:01 UTC, eqfarhad commented on pkg/controller/v1alpha/user/user_test.go
> +	roleBindings, _ := g.handler.clientset.RbacV1().RoleBindings(user.GetNamespace()).List(roleBindingListOptions)
-Solved

2020-07-06 14:05 UTC, eqfarhad commented on pkg/controller/v1alpha/user/user_test.go
> +	roleBindingListOptions = metav1.ListOptions{FieldSelector: fmt.Sprintf("metadata.name!=%s-user-aup-%s", user.GetNamespace(), user.GetName())}
-Solved

2020-07-08 09:13 UTC, bsenel requested changes
Good job! It seems we are almost there. If you can do the changes quickly, maybe we can merge the code by tomorrow?

2020-07-08 09:13 UTC, bsenel commented on pkg/controller/v1alpha/team/handler.go
> +				registration.CreateRoleBindingsByRoles(user.DeepCopy(), teamChildNamespaceStr, "Team", t.clientset)
Can you please make the clientset the first argument?

2020-07-08 09:13 UTC, bsenel commented on pkg/controller/v1alpha/team/handler.go
> +				registration.CreateRoleBindingsByRoles(userRow.DeepCopy(), teamChildNamespaceStr, "Team", t.clientset)
Same as above.

2020-07-08 09:13 UTC, bsenel commented on pkg/controller/v1alpha/user/handler.go
> +			_, err = registration.CreateServiceAccount(userCopy, "main", t.clientset)
I prefer having the clientset as the first argument.

2020-07-08 09:13 UTC, bsenel commented on pkg/controller/v1alpha/user/handler.go
> +		fmt.Printf("\nUSERAUP_MAIN= %v\n", userAUP)
Please remove this.

2020-07-08 09:13 UTC, bsenel commented on pkg/controller/v1alpha/user/handler.go
> +	return err
Can you please let me know what you wanted to do here? Since the err we return can be nil or an error, you should handle the err where you invoke this function.

It should be like below:

```
} else {
        t.sendEmail(userCopy, authorityName, "", "user-email-verification-update-malfunction")
}
return err
```

2020-07-08 09:13 UTC, bsenel commented on pkg/controller/v1alpha/user/handler.go
> +	registration.CreateSpecificRoleBindings(userCopy, t.clientset)
The clientset as the first argument.

2020-07-08 09:13 UTC, bsenel commented on pkg/controller/v1alpha/user/handler.go
> +					registration.CreateRoleBindingsByRoles(userCopy, fmt.Sprintf("%s-slice-%s", namespacePrefix, sliceRow.GetName()), "Slice", t.clientset)
Same as above.

2020-07-08 09:13 UTC, bsenel commented on pkg/controller/v1alpha/user/handler.go
> +	registration.CreateRoleBindingsByRoles(userCopy, userCopy.GetNamespace(), "Authority", t.clientset)
Same as above, the clientset.

2020-07-08 09:13 UTC, bsenel commented on pkg/controller/v1alpha/user/handler.go
> +				registration.CreateRoleBindingsByRoles(userCopy, fmt.Sprintf("%s-team-%s", userCopy.GetNamespace(), teamRow.GetName()), "Team", t.clientset)
Same as above.

2020-07-08 09:13 UTC, bsenel commented on pkg/controller/v1alpha/user/handler.go
> +	return err
It seems you are having trouble with error handling. You don't need to have an else condition there and returning the err at the end of the function is OK. 

```
if err != nil {
		...
                ...
		userOwnerReferences := t.setOwnerReferences(userCopy)
		roleBind.ObjectMeta.OwnerReferences = userOwnerReferences
		_, err = t.clientset.RbacV1().RoleBindings(userCopy.GetNamespace()).Create(roleBind)
		if err != nil {
			log.Infof("Couldn't create user-aup-%s role: %s", userCopy.GetName(), err)
		}
}
return err
```

2020-07-08 09:13 UTC, bsenel commented on pkg/node/node.go
> +		fmt.Printf("cordinates=%v", coordinates)
Please remove this.

2020-07-08 09:13 UTC, bsenel commented on pkg/node/node.go
> +func CreateJoinToken(ttl string, hostname string, clientset kubernetes.Interface) string {
Let's put the clientset in the beginning here as well.

2020-07-08 09:13 UTC, bsenel commented on pkg/node/node.go
>  func getNodeByHostname(hostname string, clientset kubernetes.Interface) (string, error) {
The clientset as the first argument.

2020-07-08 09:13 UTC, bsenel commented on pkg/registration/registration.go
> +func CreateSpecificRoleBindings(userCopy *apps_v1alpha.User, clientset kubernetes.Interface) {
The clientset...

2020-07-08 09:13 UTC, bsenel commented on pkg/registration/registration.go
> +func CreateRoleBindingsByRoles(userCopy *apps_v1alpha.User, namespace string, namespaceType string, clientset kubernetes.Interface) {
Same as above.

2020-07-08 09:13 UTC, bsenel commented on pkg/registration/registration.go
> +func CreateServiceAccount(userCopy *apps_v1alpha.User, accountType string, clientset kubernetes.Interface) (*corev1.ServiceAccount, error) {
The clientset as the first argument.

2020-07-08 09:13 UTC, bsenel commented on pkg/registration/registration.go
> +func MakeUser(user string, kubernetes kubernetes.Interface) ([]byte, int) {
Make the clientset the first argument.

2020-07-08 09:13 UTC, bsenel commented on pkg/registration/registration.go
> +func MakeUser(user string, kubernetes kubernetes.Interface) ([]byte, int) {
Use clientset rather than kubernetes.

2020-07-08 09:13 UTC, bsenel commented on pkg/registration/registration.go
> +	userNamespace, err := namespace.Create(user, kubernetes)
Same as above.

2020-07-08 09:13 UTC, bsenel commented on pkg/registration/registration.go
> +	exist, err := namespace.GetNamespaceByName(user, kubernetes)
Same as above.

2020-07-08 09:13 UTC, bsenel commented on pkg/node/node_test.go
> +		{[][]float64{{2.352700, 48.854300}}, []float64{2.3527, 2.3527, 48.8543, 48.8543}},
Can you please provide more input here?

2020-07-08 09:13 UTC, bsenel commented on pkg/controller/v1alpha/user/user_test.go
> +		}
Can you please include role bindings here?

2020-07-08 09:13 UTC, bsenel commented on pkg/controller/v1alpha/user/user_test.go
> +		}
It just tests the fake client but there is no EdgeNet functionality tested here. Do we need this part?

2020-07-08 09:13 UTC, bsenel commented on pkg/controller/v1alpha/user/user_test.go
> +		}
Can you please include user deactivation when the email address updated?

2020-07-08 09:13 UTC, bsenel commented on pkg/controller/v1alpha/user/user_test.go
> +		roleBindings, _ := g.handler.clientset.RbacV1().RoleBindings(user.GetNamespace()).Get(fmt.Sprintf("%s-user-%s", user.GetNamespace(), user.GetName()), metav1.GetOptions{})
You should check role-specific binding such as **admin, manager, and user** than user-specific one. However, the permission system is changed you can also remove the **"Updating role"** part completely.

2020-07-08 13:01 UTC, eqfarhad commented on pkg/controller/v1alpha/user/handler.go
> +	return err
the function by default doesn't return any err value, and in both case of success or err it will invoke sendEmail,
so i added error as the return of function and in any case it's going to return me the err either nil or an error.
then at test part i was checking if it throw back me nil or an error.
but i think i got your point and changed it.

2020-07-08 13:06 UTC, eqfarhad commented on pkg/controller/v1alpha/user/handler.go
> +	return err
I got your point and fixed it

2020-07-08 13:33 UTC, eqfarhad commented on pkg/controller/v1alpha/user/user_test.go
> +		}
I wanted to be sure the user got created.
one line above of this line i invoke ObjectCreated() of user. so I thought i should become sure it got work.

2020-07-08 14:03 UTC, eqfarhad commented on pkg/node/node_test.go
> +		{[][]float64{{2.352700, 48.854300}}, []float64{2.3527, 2.3527, 48.8543, 48.8543}},
sure, added more points to it

2020-07-08 14:03 UTC, eqfarhad commented on pkg/registration/registration.go
> +	exist, err := namespace.GetNamespaceByName(user, kubernetes)
-fixed

2020-07-08 14:07 UTC, eqfarhad commented on pkg/controller/v1alpha/user/user_test.go
> +		}
> It just tests the fake client but there is no EdgeNet functionality tested here. Do we need this part?

so in here I first Created a user then invoked the ObjectCreated function, and then i'm getting the user, so i thought i should check the existence of it before using it,
doesn't mean that ObjectCreated worked well?

2020-07-08 14:08 UTC, eqfarhad commented on pkg/controller/v1alpha/user/user_test.go
> +		}
-added

2020-07-08 14:08 UTC, eqfarhad commented on pkg/controller/v1alpha/user/user_test.go
> +		roleBindings, _ := g.handler.clientset.RbacV1().RoleBindings(user.GetNamespace()).Get(fmt.Sprintf("%s-user-%s", user.GetNamespace(), user.GetName()), metav1.GetOptions{})
-completely removed this part :)

2020-07-08 14:08 UTC, eqfarhad commented on pkg/registration/registration.go
> +	userNamespace, err := namespace.Create(user, kubernetes)
-fixed

2020-07-08 14:21 UTC, bsenel commented on pkg/controller/v1alpha/user/user_test.go
> +		}
You create a user in line 204 by `g.edgenetclient.AppsV1alpha().Users(fmt.Sprintf("authority-%s", g.authorityObj.GetName())).Create(g.userObj.DeepCopy())`. When you use this function, the user object already gets created. 

The thing is, it just creates the object without running any functions. Therefore, we trigger the ObjectCreated function in the handler to meet our requirements. Briefly, the ObjectCreated function doesn't create objects, that contains our functionalities.

As a result, you only test the functionality of the fake clientset here.

2020-07-08 14:26 UTC, eqfarhad commented on pkg/controller/v1alpha/user/user_test.go
> +		}
Ok i see, so i'm going to remove this part

2020-07-09 08:57 UTC, bsenel approved these changes
I think we finally got there, it seems ready to merge. 🥳 I will also improve them when I have time for this.

Congrats! 👍

2020-07-09 08:57 UTC, merged