Release 1.0 unit testing for Team and mailer custom resources
EdgeNet-project/edgenet-legacy-2024 pull request #125
Opened 2020-07-03 12:49 UTC by habdullah

Added Unit tests for Team and Mailer custom resources. Test coverage ~60% and ~80% respectively.

2020-07-03 17:37 UTC, bsenel requested changes
You also did a good job and it is OK! 👍 However, I commented on some parts to be fixed.

Can you please make Kubernetes client and EdgeNet client very first parameters at the functions in all packages, as same as I asked @eqfarhad for?

By the way, it would be great if you update the comments and other parts by taking the typo into consideration.

2020-07-03 17:37 UTC, bsenel commented on pkg/controller/v1alpha/team/handler.go
> +func (t *Handler) Init(kubernetes kubernetes.Interface, edgenet versioned.Interface) error {
Why does **Init** return an error?

2020-07-03 17:37 UTC, bsenel commented on pkg/node/node.go
> +	var err error
You don't need to add `var err error` here.` _, err := clientset.CoreV1().Nodes().Patch(hostname, types.JSONPatchType, nodesJSON)` should also work.

2020-07-03 17:37 UTC, bsenel commented on pkg/registration/registration.go
> +	client := testclient.NewSimpleClientset()
You shouldn't do that. Here, you create **a fake client** and pass it into a function in `registration.go`, which means this function doesn't work properly anymore. What you should is replacing the `func MakeUser(user string) ([]byte, int)` with `func MakeUser(clientset kubernetes.Interface, user string) ([]byte, int)`.

2020-07-03 17:37 UTC, bsenel commented on pkg/controller/v1alpha/team/controller_test.go
> +	g.edgenetclient.AppsV1alpha().Authorities().Create(g.authorityObj.DeepCopy())
Do you need this part since you create an authority in Init() function at the 15th line?

2020-07-03 17:37 UTC, bsenel commented on pkg/controller/v1alpha/team/controller_test.go
> +	// g.handler.ObjectCreated(g.teamObj.DeepCopy())
Let's remove this line 26 that is a comment.

2020-07-03 17:37 UTC, bsenel commented on pkg/controller/v1alpha/team/controller_test.go
> +	}
You test the Team Custom Resource. Is it necessary?

2020-07-03 17:37 UTC, bsenel commented on pkg/controller/v1alpha/team/controller_test.go
> +	}
It would be a better way if you do check the role bindings of the user added to the team.

2020-07-03 17:37 UTC, bsenel commented on pkg/controller/v1alpha/team/team_test.go
> +const established = "Established"
Do we really need them?

2020-07-03 17:37 UTC, bsenel commented on pkg/controller/v1alpha/team/team_test.go
> +	authorityRequestObj apps_v1alpha.AuthorityRequest
It is not in use in this unit testing file.

2020-07-03 17:37 UTC, bsenel commented on pkg/controller/v1alpha/team/team_test.go
> +	}
Please remove this part as it is unused.

2020-07-03 17:37 UTC, bsenel commented on pkg/controller/v1alpha/team/team_test.go
> +	})
It doesn't test any functionality developed by EdgeNet here but the fake client. You should include the changes triggered by ObjectCreated().

2020-07-03 17:37 UTC, bsenel commented on pkg/controller/v1alpha/team/team_test.go
> +		field.enabled = true
The enabled status of the team should already be true when created. So, you should test by a false value.

2020-07-03 17:37 UTC, bsenel commented on pkg/controller/v1alpha/team/team_test.go
> +}
You should include the changes, such as role bindings, triggered by ObjectUpdated().

2020-07-03 17:37 UTC, bsenel commented on pkg/controller/v1alpha/team/team_test.go
> +	}
It is related to the fake client.

2020-07-03 17:37 UTC, bsenel commented on pkg/controller/v1alpha/team/team_test.go
> +}
I am not sure if the fake client runs a garbage collector but you may consider checking if the child namespace is deleted.

2020-07-03 17:37 UTC, bsenel commented on pkg/node/node_test.go
> +		}}
You may consider having a test group in this unit testing file as well.

2020-07-03 17:37 UTC, bsenel commented on pkg/node/node_test.go
> +}
All of them is a comment.

2020-07-03 17:37 UTC, bsenel commented on pkg/mailer/mailer_test.go
> +	smtpServer.Username = "yy"
Let's update this part according to the information below. It will use the mailtrap.io solution, thanks to Ciro.

```
host: "smtp.mailtrap.io"
port: 2525
from: "support@planet-lab.eu"
username: "35372f352f7f11"
password: "8260a9b6047ac5"
to: "support@planet-lab.eu"
```

2020-07-03 17:37 UTC, bsenel commented on pkg/mailer/mailer_test.go
> +		}
You may also include the Send function of the mailer package.

2020-07-06 13:01 UTC, habdullah commented on pkg/controller/v1alpha/team/controller_test.go
> +	g.edgenetclient.AppsV1alpha().Authorities().Create(g.authorityObj.DeepCopy())
No it is not needed. Removed

2020-07-06 13:01 UTC, habdullah commented on pkg/controller/v1alpha/team/controller_test.go
> +	// g.handler.ObjectCreated(g.teamObj.DeepCopy())
Removed

2020-07-06 13:02 UTC, habdullah commented on pkg/controller/v1alpha/team/controller_test.go
> +	}
It is not. Removed

2020-07-06 13:02 UTC, habdullah commented on pkg/controller/v1alpha/team/handler.go
> +func (t *Handler) Init(kubernetes kubernetes.Interface, edgenet versioned.Interface) error {
It is a type and should be removed

2020-07-06 13:07 UTC, habdullah commented on pkg/controller/v1alpha/team/team_test.go
> +const established = "Established"
It was used by AuthorityRequestbject definition. Both removed

2020-07-06 13:07 UTC, habdullah commented on pkg/controller/v1alpha/team/team_test.go
> +	authorityRequestObj apps_v1alpha.AuthorityRequest
Removed

2020-07-07 01:34 UTC, habdullah commented on pkg/controller/v1alpha/team/team_test.go
> +	}
It is a check to make sure team exists before we add teamowner references to it

2020-07-07 09:10 UTC, habdullah commented on pkg/mailer/mailer_test.go
> +		}
But the send function does not return anything, is there a way to verify that email was really sent?

2020-07-08 09:25 UTC, bsenel commented on pkg/controller/v1alpha/team/team_test.go
> +	}
So, then you shouldn't throw a testing error here as it is not related to any EdgeNet functionality. You may log the error but I am not sure it is necessary.

2020-07-08 09:27 UTC, bsenel commented on pkg/mailer/mailer_test.go
> +		}
You can return an error at the end of the Send function to do that.

2020-07-08 09:59 UTC, bsenel requested changes
Please don't get confused about the clientset functionality and the EdgeNet functionality. When you use the clientset, it creates, updates, and deletes objects. On the other side, we have an event handler that triggers related EdgeNet functions according to the event type.

Let's try to get this done until the meeting tomorrow.

2020-07-08 09:59 UTC, bsenel commented on pkg/controller/v1alpha/team/handler.go
> +				registration.CreateRoleBindingsByRoles(user.DeepCopy(), teamChildNamespaceStr, "Team", t.clientset)
Can you please put the clientset as the first argument?

2020-07-08 09:59 UTC, bsenel commented on pkg/controller/v1alpha/team/handler.go
> +				registration.CreateRoleBindingsByRoles(userRow.DeepCopy(), teamChildNamespaceStr, "Team", t.clientset)
Same as above.

2020-07-08 09:59 UTC, bsenel commented on pkg/mailer/mailer_test.go
> +	smtpServer.Username = "35372f352f7f11"
Is it possible to create `config/smtp_test.yaml` file for this part instead of keeping this information here?

2020-07-08 09:59 UTC, bsenel commented on pkg/controller/v1alpha/team/controller_test.go
> +	}
I couldn't see the role binding check here, am I missing something?

2020-07-08 09:59 UTC, bsenel commented on pkg/controller/v1alpha/team/team_test.go
> +		}
You don't test any EdgeNet functionality here, so, you shouldn't throw a testing error. Between line 166 and line 169, you test the EdgeNet functionality in a good way.

2020-07-08 09:59 UTC, bsenel commented on pkg/controller/v1alpha/team/team_test.go
> +	})
Kubernetes clients don't allow to create two objects with the same name in a namespace. So, can you please remove this part?

2020-07-08 09:59 UTC, bsenel commented on pkg/controller/v1alpha/team/team_test.go
> +		g.handler.ObjectUpdated(g.teamObj.DeepCopy(), field)
The same issue here. You only test the capability of Kubernetes client. You should include Slice and Role Binding existence check here.

2020-07-08 12:42 UTC, habdullah commented on pkg/controller/v1alpha/team/controller_test.go
> +	}
I missed this. Adding here aswell

2020-07-08 12:44 UTC, habdullah commented on pkg/mailer/mailer_test.go
> +		}
I am now executing send() inside a Run test

2020-07-08 16:02 UTC, habdullah commented on pkg/mailer/mailer_test.go
> +	smtpServer.Username = "35372f352f7f11"
Do you want the unit test to create the smtp_test.yaml file temporarily, read it, test all the functions and then delete it?
or do you want the unit test to expect the file to be present in config/smtp_test.yaml?

2020-07-09 16:22 UTC, bsenel commented on pkg/controller/v1alpha/team/team_test.go
> +		}
You don't test any functionality of EdgeNet here.

2020-07-10 09:45 UTC, bsenel approved these changes
Congrats! 👍 

It seems to be ready to go. I will also improve those when I have time for it. ⌚

2020-07-10 09:45 UTC, merged