Release 1.0 unit testing
EdgeNet-project/edgenet-legacy-2024 pull request #127
Opened 2020-07-22 11:45 UTC by habdullah

Adapted unit tests for team, authority request , user registration request pkg
Added unit test for slice pkg

2020-07-23 15:59 UTC, bsenel requested changes
This is good in general. Please pay attention to spelling rules and the distinction of lower case and upper case.

I am waiting for you to make changes.

2020-07-23 15:59 UTC, bsenel commented on configs/smtp_test_template.yaml
> -to: "yyz@xx.fr"
Why did you delete the SMTP test template from the configs folder?

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/team/controller_test.go
> +	user, _:= g.edgenetclient.AppsV1alpha().Users(fmt.Sprintf("authority-%s", g.authorityObj.GetName())).Get("user1", metav1.GetOptions{})
Add a space before the equal sign.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/team/team_test.go
> +			Enabled: true,
As of now, you should put the enabled into the authority spec.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/team/team_test.go
> -			Active: true,
Please put the active information into the spec.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/user/handler.go
> +			err = nil
What is the reason of this?

2020-07-23 15:59 UTC, bsenel commented on pkg/node/node.go
> +	"edgenet/pkg/node/infrastructure"
Please be careful about the pattern of imports.

2020-07-23 15:59 UTC, bsenel commented on pkg/registration/registration.go
> +	"k8s.io/client-go/kubernetes"
Same as above, the pattern of imports.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/authorityrequest/authorityrequest_test.go
> +			EmailVerified: true,
I think it should be false as default and you should update that in your test.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/authorityrequest/authorityrequest_test.go
> +			Email:     "userName@edge-net.org",
Please put the active information into the spec.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/authorityrequest/authorityrequest_test.go
> +	AuthorityRequestObj := apps_v1alpha.AuthorityRequest{
Replace the variable of `AuthorityRequestObj` with `authorityRequestObj` to remove unnecessary declaration.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/authorityrequest/authorityrequest_test.go
> +	g.authorityRequestObj = AuthorityRequestObj
Same as above, `AuthorityRequestObj`.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/authorityrequest/authorityrequest_test.go
> +		if AR.Status.Message == nil {
Can we create an array that contains the error messages? It would be great to have and that array would allow us to make a comparison here? Does it make sense?

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/authorityrequest/controller.go
> +
Please remove this blank line.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/authorityrequest/handler.go
> +		var err error
You don't need to put this here as you put it at line 76.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/authorityrequest/handler.go
>  		if err == nil {
You should remove the condition of `if err == nil {...}` that was checking the Init error.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/authorityrequest/handler.go
>  			if err == nil {
Same as above. You should remove the condition of `if err == nil {...}` that was checking the Init error.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/slice/controller_test.go
> +	}
Please check this out by the expiration date.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/slice/controller_test.go
> +	}
Frankly, you don't test any EdgeNet functionality here.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/slice/handler.go
>  		if err == nil {
The if condition here is not necessary.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/slice/handler.go
>  				if err == nil {
Same as above.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/slice/slice_test.go
> +			Email:     "userName@edge-net.org",
Please put the active information herein.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/slice/slice_test.go
> +	//invoke ObjectCreated to create namespace
Put the comment into the related part.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/slice/slice_test.go
> +	})
Can you please also add a resource quota check here?

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/slice/slice_test.go
> +		}
Please also check the resource quota here.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/slice/slice_test.go
> +		}
Check the expiration date accordingly to the slice profile.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/userregistrationrequest/controller_test.go
> +	User, _ := g.edgenetclient.AppsV1alpha().Users(fmt.Sprintf("authority-%s", g.authorityObj.GetName())).Get(g.userRegistrationObj.GetName(), metav1.GetOptions{})
Make the first letter lowercase here.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/userregistrationrequest/handler.go
>  			if err == nil {
Remove the if condition here.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/userregistrationrequest/handler.go
>  			if err == nil {
Same as above, remove the if condition.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/userregistrationrequest/handler.go
>  				if err == nil {
Same as above.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/userregistrationrequest/handler.go
>  				if err == nil {
Same as above.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/userregistrationrequest/handler.go
> +	usersRaw, _ := t.edgenetClientset.AppsV1alpha().Users(URRCopy.GetNamespace()).Get(URRCopy.GetName(), metav1.GetOptions{})
Change the variable name of `usersRaw`, for example, `userObj`.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/authorityrequest/handler.go
> +	authorityRaw, _ := t.edgenetClientset.AppsV1alpha().Authorities().Get(authorityRequestCopy.GetName(), metav1.GetOptions{})
Change the variable name to `authorityObj`.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/userregistrationrequest/userregistrationrequest_test.go
> +			Email:     "userName@edge-net.org",
Put the active information herein.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/userregistrationrequest/userregistrationrequest_test.go
> +		}
Same as above. Please create an array for error messages if possible.

2020-07-23 15:59 UTC, bsenel commented on pkg/controller/v1alpha/userregistrationrequest/userregistrationrequest_test.go
> +		User, _ := g.edgenetclient.AppsV1alpha().Users(fmt.Sprintf("authority-%s", g.authorityObj.GetName())).Get(g.userRegistrationObj.GetName(), metav1.GetOptions{})
Make the first letter lowercase.

2020-07-25 16:34 UTC, habdullah commented on configs/smtp_test_template.yaml
> -to: "yyz@xx.fr"
I was unsure about this, When I was merging your changes It showed me that this file was deleted in your changes. I should have kept this.

2020-07-25 16:42 UTC, habdullah commented on pkg/controller/v1alpha/team/team_test.go
> +			Enabled: true,
It is already in authority spec.I think it is the Github layout which is making it look wrong.

2020-07-25 16:43 UTC, habdullah commented on pkg/controller/v1alpha/team/team_test.go
> -			Active: true,
done

2020-07-25 16:50 UTC, habdullah commented on pkg/controller/v1alpha/user/handler.go
> +			err = nil
The emailverificationhandler doesn't return error anymore. Removing err check.

2020-07-25 17:01 UTC, habdullah commented on pkg/controller/v1alpha/authorityrequest/authorityrequest_test.go
> +		if AR.Status.Message == nil {
I'm not sure I follow...

2020-07-25 17:03 UTC, habdullah commented on pkg/controller/v1alpha/authorityrequest/handler.go
> +		var err error
That line is outside the scope. Removing err check

2020-07-25 17:03 UTC, habdullah commented on pkg/controller/v1alpha/authorityrequest/handler.go
>  		if err == nil {
Removed

2020-07-25 21:23 UTC, habdullah commented on pkg/controller/v1alpha/slice/controller_test.go
> +	}
removed

2020-07-25 21:44 UTC, habdullah commented on pkg/controller/v1alpha/userregistrationrequest/userregistrationrequest_test.go
> +		}
Adding array for this package

2020-07-27 07:33 UTC, bsenel requested changes
We are almost there.

2020-07-27 07:33 UTC, bsenel commented on pkg/controller/v1alpha/authorityrequest/authorityrequest_test.go
> +		if AR.Status.Message == nil {
I mean let's have an array of status messages that we defined to make a comparison here. For example, which status message do we expect to have here?

2020-07-27 07:33 UTC, bsenel commented on pkg/controller/v1alpha/authorityrequest/authorityrequest_test.go
> +}
Let's put a dictionary of status messages as a const variable in the controller of authority requests.

2020-07-27 07:33 UTC, bsenel commented on pkg/controller/v1alpha/authorityrequest/handler.go
>  		if err == nil {
What is the purpose of having this err variable here?

2020-07-27 07:33 UTC, bsenel commented on pkg/controller/v1alpha/authorityrequest/handler.go
>  			if err == nil {
Same as above, why does this err variable stand here?

2020-07-27 07:33 UTC, bsenel commented on pkg/controller/v1alpha/emailverification/controller_test.go
> +	g.EVObj.Spec.Kind = "email"
We typically don't change the kind, so, maybe we should remove that and only verify the object here.

2020-07-27 07:33 UTC, bsenel commented on pkg/controller/v1alpha/userregistrationrequest/handler.go
> +			var err error
Do we need to have it here?

2020-07-27 07:33 UTC, bsenel commented on pkg/controller/v1alpha/userregistrationrequest/handler.go
> +
Remove the blank line.

2020-07-27 07:33 UTC, bsenel commented on pkg/controller/v1alpha/userregistrationrequest/handler.go
> +				var err error
Do we need to have it here?

2020-07-27 07:33 UTC, bsenel commented on pkg/controller/v1alpha/userregistrationrequest/userregistrationrequest_test.go
> +			EmailVerified: true,
This should be false by default.

2020-07-27 07:33 UTC, bsenel commented on pkg/controller/v1alpha/userregistrationrequest/userregistrationrequest_test.go
> +		t.Log(userRequest.Status.Expires)
I think you can remove the log here.

2020-07-27 07:33 UTC, bsenel commented on pkg/controller/v1alpha/userregistrationrequest/userregistrationrequest_test.go
> +		User, _ := g.edgenetclient.AppsV1alpha().Users(fmt.Sprintf("authority-%s", g.authorityObj.GetName())).Get(g.userRegistrationObj.GetName(), metav1.GetOptions{})
Please replace `User` with `user`.

2020-07-27 07:33 UTC, bsenel commented on pkg/controller/v1alpha/acceptableusepolicy/controller_test.go
> +
Please remove this blank line.

2020-07-27 07:33 UTC, bsenel commented on pkg/controller/v1alpha/emailverification/emailverfication_test.go
> +		g.EVObj.Spec.Kind = "email"
As I mentioned at the email verification test, we don't typically change the kind.

2020-07-27 13:22 UTC, habdullah commented on pkg/controller/v1alpha/userregistrationrequest/handler.go
> +			var err error
Line 90 was referencing it. Replacing reference with empty string

2020-07-27 13:24 UTC, habdullah commented on pkg/controller/v1alpha/userregistrationrequest/handler.go
> +				var err error
Line 148 was referencing it. Replaced with empty string

2020-07-27 13:27 UTC, habdullah commented on pkg/controller/v1alpha/emailverification/emailverfication_test.go
> +		g.EVObj.Spec.Kind = "email"
This line was testing the handler functionality which deletes the EV if it is maliciously changed. Removing.

2020-07-28 16:28 UTC, bsenel requested changes
Pay more attention. Let's get this done!

2020-07-28 16:28 UTC, bsenel commented on pkg/controller/v1alpha/acceptableusepolicy/acceptableusepolicy_test.go
> +	//invoke ObjectCreated to create namespace
Can you please fit this comment into the general comment pattern?

2020-07-28 16:28 UTC, bsenel commented on pkg/controller/v1alpha/acceptableusepolicy/acceptableusepolicy_test.go
> +	//invoke ObjectCreated to create namespace
Please do that in each file.

2020-07-28 16:28 UTC, bsenel commented on pkg/controller/v1alpha/acceptableusepolicy/controller.go
> +
It is better if we keep the dict in the test files. However, it would be great if we have a status dictionary here.

2020-07-28 16:28 UTC, bsenel commented on pkg/controller/v1alpha/authority/controller.go
> +
I would put this into the unit test file.

2020-07-28 16:28 UTC, bsenel commented on pkg/controller/v1alpha/authorityrequest/authorityrequest_test.go
> +	//invoke ObjectCreated to create namespace
`// Invoke ...`

2020-07-28 16:28 UTC, bsenel commented on pkg/controller/v1alpha/authorityrequest/authorityrequest_test.go
> +		if AR.Status.Message == nil {
The code still doesn't meet what we need here.

2020-07-28 16:28 UTC, bsenel commented on pkg/controller/v1alpha/authorityrequest/controller.go
> +
Move into the test file.

2020-07-28 16:28 UTC, bsenel commented on pkg/controller/v1alpha/authorityrequest/handler.go
> +		var err error
Do you need this err variable here?

2020-07-28 16:28 UTC, bsenel commented on pkg/controller/v1alpha/authorityrequest/handler.go
> +			var err error
Remove the err variable if it is not required.

2020-07-28 16:28 UTC, bsenel commented on pkg/controller/v1alpha/emailverification/controller.go
> +}
Move to the test file.

2020-07-28 16:28 UTC, bsenel commented on pkg/controller/v1alpha/emailverification/controller_test.go
> +	// Checking if user registration transitioned to user after update
???

2020-07-28 16:28 UTC, bsenel commented on pkg/controller/v1alpha/emailverification/emailverfication_test.go
> +const success = "Successful"
Where do you use this const variable?

2020-07-28 16:28 UTC, bsenel commented on pkg/controller/v1alpha/slice/controller.go
> +
Move this dict...

2020-07-28 16:28 UTC, bsenel commented on pkg/controller/v1alpha/slice/controller_test.go
> +
Remove the blank line.

2020-07-28 16:28 UTC, bsenel commented on pkg/controller/v1alpha/team/controller.go
> +
Don't put this here.

2020-07-28 16:28 UTC, bsenel commented on pkg/controller/v1alpha/totalresourcequota/controller.go
> +
Move...

2020-07-28 16:28 UTC, bsenel commented on pkg/controller/v1alpha/userregistrationrequest/controller.go
> +}
Not here.

2020-07-28 16:28 UTC, bsenel commented on pkg/controller/v1alpha/userregistrationrequest/userregistrationrequest_test.go
> +		User, _ := g.edgenetclient.AppsV1alpha().Users(fmt.Sprintf("authority-%s", g.authorityObj.GetName())).Get(g.userRegistrationObj.GetName(), metav1.GetOptions{})
?

2020-07-29 13:09 UTC, habdullah commented on pkg/controller/v1alpha/acceptableusepolicy/controller.go
> +
Farhad will push the status dictionary with his code

2020-07-30 16:45 UTC, bsenel commented on pkg/controller/v1alpha/authorityrequest/authorityrequest_test.go
> +		if AR.Status.Message == nil {
OK, I will do that myself later.

2020-07-30 16:50 UTC, bsenel commented on pkg/controller/v1alpha/userregistrationrequest/userregistrationrequest_test.go
> +		User, _ := g.edgenetclient.AppsV1alpha().Users(fmt.Sprintf("authority-%s", g.authorityObj.GetName())).Get(g.userRegistrationObj.GetName(), metav1.GetOptions{})
OK, I will do that myself later.

2020-07-30 16:58 UTC, bsenel approved these changes
Very good! 

I put here a comment as a friendly reminder for me. There are two things here to fix. First; a comparison of the status message should be more particularized at `authorityrequest_test.go` in the 184th line, and second; we should make the first letter of `User` lowercase at `userregistrationrequest_test.go` if it is not necessary. However, I will handle them after the merge.

Congrats! 👍

2020-07-30 16:58 UTC, merged