Release 1.0 unit testing - updated structure and new unit tests
EdgeNet-project/edgenet-legacy-2024 pull request #132
Opened 2020-07-29 15:01 UTC by eqfarhad

+ Added unit test for remoteip, permission, utils, registration
* Updated all packages in order to use values from a dictionary for status messages
* Updated the previous code part with new structure

2020-07-30 18:17 UTC, bsenel requested changes
There are plenty of things to do. Above all, please check with Hammad to avoid conflicts.

2020-07-30 18:17 UTC, bsenel commented on configs/smtp_test_template.yaml
> -to: "yyz@xx.fr"
Why did you delete this file? We changed the name of the folder from **config** to **configs**. It might have caused confusion.

2020-07-30 18:17 UTC, bsenel commented on pkg/controller/v1alpha/authorityrequest/handler.go
> +		var err error
Do we need the **err** variable here?

2020-07-30 18:17 UTC, bsenel commented on pkg/controller/v1alpha/authorityrequest/handler.go
> +			var err error
Is it necessary to define here, the **err** var?

2020-07-30 18:17 UTC, bsenel commented on pkg/controller/v1alpha/authorityrequest/handler.go
> +
Please remove the blank line.

2020-07-30 18:17 UTC, bsenel commented on pkg/controller/v1alpha/emailverification/controller.go
> +	c.handler.Init(clientset, edgenetClientset)
Hammad already developed this part. Are you both in sync?

2020-07-30 18:17 UTC, bsenel commented on pkg/controller/v1alpha/emailverification/handler.go
> +	t.edgenetClientset = edgenet
Same as above. Hammad already has worked on this part. Please check with him to avoid conflict.

2020-07-30 18:17 UTC, bsenel commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +func (t *Handler) sendEmail(NCCopy *apps_v1alpha.NodeContribution) error {
If you want to return an error here, it should be related to sending email function. You return a node contribution failed error here, which is not relevant here. Probably, we update the status before this function run, where is the place to return this error.

2020-07-30 18:17 UTC, bsenel commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +	uninstallationCommands, err := getUninstallCommands(conn, []byte(""))
We discussed that several times, you shouldn't update the functions like this to fit your unit test. Is there a functionality of node contribution that we use at the fakeOS part? If the answer is no, it is only focused on a solution to fulfilling a unit test, which is not a good way to do so.

2020-07-30 18:17 UTC, bsenel commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +	installationCommands, err := getInstallCommands(conn, nodeName, node.GetKubeletVersion()[1:], []byte(""))
The fakeOS...

2020-07-30 18:17 UTC, bsenel commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +	configurationCommands, err := getReconfigurationCommands(conn, hostname, []byte(""))
Same as above.

2020-07-30 18:17 UTC, bsenel commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +func getInstallCommands(conn *ssh.Client, hostname string, kubernetesVersion string, fakeOS []byte) ([]string, error) {
The fakeOS, same as above.

2020-07-30 18:17 UTC, bsenel commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +	} else {
What is the reason for this? Is this just for a unit test to fulfill some requirements?

2020-07-30 18:17 UTC, bsenel commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +func getUninstallCommands(conn *ssh.Client, fakeOS []byte) ([]string, error) {
Same as above.

2020-07-30 18:17 UTC, bsenel commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +	} else {
fakeOS....

2020-07-30 18:17 UTC, bsenel commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +	} else {
fakeOS, same as above.

2020-07-30 18:17 UTC, bsenel commented on pkg/controller/v1alpha/nodecontribution/nodecontribution_test.go
>  package nodecontribution
You should update this unit test.

2020-07-30 18:17 UTC, bsenel commented on pkg/controller/v1alpha/slice/handler.go
> +		TRQHandler.Init(t.clientset, t.edgenetClientset)
Hammad already worked on this part. Please check with him.

2020-07-30 18:17 UTC, bsenel commented on pkg/controller/v1alpha/slice/handler.go
> +				TRQHandler.Init(t.clientset, t.edgenetClientset)
Please check with Hammad.

2020-07-30 18:17 UTC, bsenel commented on pkg/controller/v1alpha/team/controller_test.go
> +	if !team.Spec.Enabled {
Please check with Hammad...

2020-07-30 18:17 UTC, bsenel commented on pkg/controller/v1alpha/team/team_test.go
> +			Enabled:     true,
Contact Hammad.

2020-07-30 18:17 UTC, bsenel commented on pkg/controller/v1alpha/team/team_test.go
> +			Enabled: true,
Same as above.

2020-07-30 18:17 UTC, bsenel commented on pkg/controller/v1alpha/userregistrationrequest/handler.go
> +					URRCopy = URRCopyUpdated
Hammad already updated these parts. Are you in sync?

2020-07-30 18:17 UTC, bsenel commented on pkg/controller/v1alpha/userregistrationrequest/handler.go
> +				URRCopy.Status.Message = []string{statusDict["email-fail"]}
Same as above.

2020-07-30 18:17 UTC, bsenel commented on pkg/controller/v1alpha/userregistrationrequest/handler.go
> +					URRCopy.Status.Message = []string{statusDict["email-fail"]}
Check with Hammad.

2020-07-30 18:17 UTC, bsenel commented on pkg/mailer/mailer_test.go
> -
Hammad already did this.

2020-07-30 18:17 UTC, bsenel commented on pkg/permission/permission_test.go
> +	})
I don't think you check anything other than k8s functionality here.

2020-07-30 18:17 UTC, bsenel commented on pkg/permission/permission_test.go
> +	}
You can check those together as you did at the **TestCreateClusterRoles** function.

2020-07-30 18:17 UTC, bsenel commented on pkg/permission/permission_test.go
> +		userRoleBind, errS := g.client.RbacV1().RoleBindings(g.userObj.GetNamespace()).Get(fmt.Sprintf("%s-%s-authority-admin", g.userObj.GetNamespace(), g.userObj.GetName()), metav1.GetOptions{})
Name **errS** more explicitly.

2020-07-30 18:17 UTC, bsenel commented on pkg/registration/registration.go
> +	timeout := time.After(15 * time.Minute)
Why do you prefer to have a timeout of 15 minutes here?

2020-07-30 18:17 UTC, bsenel commented on pkg/controller/v1alpha/user/user_test.go
> +			EmailVerified: true,
It should be false by default.

2020-07-30 18:30 UTC, eqfarhad commented on configs/smtp_test_template.yaml
> -to: "yyz@xx.fr"
> Why did you delete this file? We changed the name of the folder from **config** to **configs**. It might have caused confusion.

True, we changed it.
my question is why we need this file?(we didn't have it before merging Hammad PR)
we have smtp_template.yaml in configs with same data and we can use that for our unit tests.

2020-07-30 18:42 UTC, eqfarhad commented on pkg/controller/v1alpha/authorityrequest/handler.go
> +		var err error
`				authorityRequestCopy.Status.Message = []string{statusDict["authority-failed"], err.Error()}
`
True, I had a above line so i kept the variable, currently Hammad changed it to:
`authorityRequestCopy.Status.Message = []string{"Authority establishment failed", ""}` 

so I will change and i think it's better to remove the last empty part "" completely

2020-07-30 18:45 UTC, eqfarhad commented on pkg/controller/v1alpha/authorityrequest/handler.go
> +			var err error
True, I will do as same as the previous one (upper comment)

2020-07-30 18:47 UTC, eqfarhad commented on pkg/controller/v1alpha/authorityrequest/handler.go
> +
Done

2020-07-30 19:22 UTC, eqfarhad commented on pkg/controller/v1alpha/team/controller_test.go
> +	if !team.Spec.Enabled {
I believe that Enabled is in Spec, and it's not working with current code.
https://github.com/EdgeNet-project/edgenet/blob/1a60d0c79ec170b828b4fcd2e3e494c457ba35cd/pkg/apis/apps/v1alpha/types.go#L214

2020-07-30 19:37 UTC, eqfarhad commented on pkg/controller/v1alpha/slice/handler.go
> +		TRQHandler.Init(t.clientset, t.edgenetClientset)
> Hammad already worked on this part. Please check with him.

True, but i had to change some parts of these pkgs in order to my test work,

btw i believe this line should be changed, because:
1- why we are saving the result in "err" while that function is not throwing back us anything
2-how would this line get run, without passing the necessary argument the function expected

here is the TRQHandler.Init function=
https://github.com/EdgeNet-project/edgenet/blob/1a60d0c79ec170b828b4fcd2e3e494c457ba35cd/pkg/controller/v1alpha/totalresourcequota/handler.go#L51

2020-07-30 19:38 UTC, eqfarhad commented on pkg/controller/v1alpha/slice/handler.go
> +				TRQHandler.Init(t.clientset, t.edgenetClientset)
Same as above:

i believe this line should be changed, because:
1- why we are saving the result in "err" while that function is not throwing back us anything
2-how would this line get run, without passing the necessary argument the function expected

here is the TRQHandler.Init function=
https://github.com/EdgeNet-project/edgenet/blob/1a60d0c79ec170b828b4fcd2e3e494c457ba35cd/pkg/controller/v1alpha/totalresourcequota/handler.go#L51

2020-07-30 19:51 UTC, eqfarhad commented on pkg/controller/v1alpha/emailverification/controller.go
> +	c.handler.Init(clientset, edgenetClientset)
True, it's actually Hammad part, but in order to some part of my uni test work i needed to modify in same way as he did.
I guess there shouldn't be problem as right now as i checked the codes are exactly the same

2020-07-30 19:53 UTC, eqfarhad commented on pkg/controller/v1alpha/emailverification/handler.go
> +	t.edgenetClientset = edgenet
Same as above, in order to some part of my unit test work i needed to modify this part of the files.
right now it's completely the same as Hammad and current version of unit test branch.

2020-07-30 19:59 UTC, eqfarhad commented on pkg/controller/v1alpha/team/team_test.go
> +			Enabled:     true,
I see, i didn't actually change anything here.
sounds like Hammad had this value as true in pervious PR which got merged before new structure and i had to pull it after new structure and i have these files as well, and in recent PR he changed it to false, i will do the same then.

2020-07-30 20:00 UTC, eqfarhad commented on pkg/controller/v1alpha/team/team_test.go
> +			Enabled: true,
Done (Same as above)

2020-07-30 20:33 UTC, eqfarhad commented on pkg/controller/v1alpha/userregistrationrequest/handler.go
> +					URRCopy = URRCopyUpdated
True, I just changed the status message part,
and also had to change some parts again to my unit test work as well.

right now i changed my files as same as Hammad, only the status message part is different.

2020-07-30 20:33 UTC, eqfarhad commented on pkg/controller/v1alpha/userregistrationrequest/handler.go
> +				URRCopy.Status.Message = []string{statusDict["email-fail"]}
right now i changed my files as same as Hammad, only the status message part is different.

2020-07-30 20:38 UTC, eqfarhad commented on pkg/mailer/mailer_test.go
> -
completely true, however i had to make this changes to my files as well. otherwise i had error.

2020-07-30 21:26 UTC, eqfarhad commented on pkg/permission/permission_test.go
> +	})
i tested the functionality in the upper sub-test of this function,
and by calling it again, i wanted to check if it's going to give me an error as it existed before or not;
currently it's returning this error:
`clusterroles.rbac.authorization.k8s.io "authority-edgenet" already exists`

2020-07-30 21:29 UTC, eqfarhad commented on pkg/permission/permission_test.go
> +	}
True, I changed it.

2020-07-30 21:30 UTC, eqfarhad commented on pkg/permission/permission_test.go
> +		userRoleBind, errS := g.client.RbacV1().RoleBindings(g.userObj.GetNamespace()).Get(fmt.Sprintf("%s-%s-authority-admin", g.userObj.GetNamespace(), g.userObj.GetName()), metav1.GetOptions{})
Sure, done.

2020-07-30 22:42 UTC, eqfarhad commented on pkg/registration/registration.go
> +	timeout := time.After(15 * time.Minute)
for sure it's an mistake, I corrected it.

2020-07-30 22:44 UTC, eqfarhad commented on pkg/controller/v1alpha/user/user_test.go
> +			EmailVerified: true,
fixed it.

2020-07-30 23:23 UTC, eqfarhad commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +func (t *Handler) sendEmail(NCCopy *apps_v1alpha.NodeContribution) error {
True and make sense, fixed it.

2020-07-30 23:33 UTC, eqfarhad commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +	uninstallationCommands, err := getUninstallCommands(conn, []byte(""))
> We discussed that several times, you shouldn't update the functions like this to fit your unit test. Is there a functionality of node contribution that we use at the fakeOS part? If the answer is no, it is only focused on a solution to fulfilling a unit test, which is not a good way to do so.

I see, i wanted to bypass the SSH argument of these functions and fulfilling this requirement, and to do so i was adding extra argument.
btw you are totally right, and sorry.

I just updated it and now i'm using flag, hope this be a better way to handling it.

2020-07-31 09:41 UTC, bsenel requested changes
There are some to fix.

2020-07-31 09:41 UTC, bsenel commented on pkg/controller/v1alpha/team/team_test.go
> -
Why did you delete this test function? I see Hammad's version includes this part at https://github.com/EdgeNet-project/edgenet/blob/release-1.0-unit-testing/pkg/controller/v1alpha/team/team_test.go.

2020-07-31 09:41 UTC, bsenel commented on pkg/permission/permission_test.go
> +	})
OK, I mean this is not a functionality of EdgeNet. When you use k8s client to create an object that already exists, it automatically throws that error. So, you don't test any EdgeNet feature here.

2020-07-31 09:41 UTC, bsenel commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +	} else {
You shouldn't write code to only provide unit test capabilities. Please find another way to do so, for example, by a fake SSH client that returns a fake OS.

2020-07-31 09:41 UTC, bsenel commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +	} else {
Same as above.

2020-07-31 09:41 UTC, bsenel commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +	} else {
Same as above.

2020-07-31 09:46 UTC, eqfarhad commented on pkg/permission/permission_test.go
> +	})
True, I'm going to remove this part

2020-07-31 09:48 UTC, bsenel commented on pkg/controller/v1alpha/authorityrequest/handler.go
> +		var err error
It seems this is something I missed, @habdullah. You were doing the right thing by using `authorityRequestCopy.Status.Message = []string{statusDict["authority-failed"], err.Error()}`. Please keep that form otherwise it doesn't make sense.

On the other hand, I pointed out the err variable at line 88, `var err error`, do we need to define this variable there?

2020-07-31 09:51 UTC, eqfarhad commented on pkg/controller/v1alpha/team/team_test.go
> -
yup, fixed it.

2020-07-31 09:52 UTC, bsenel commented on configs/smtp_test_template.yaml
> -to: "yyz@xx.fr"
@habdullah  and I just wanted to provide a test SMTP configuration to users. It would allow users to configure a test environment as well. But your opinions also make sense, so, I get undecided. Maybe we can directly use the `smpt.yaml` for testing purposes as well. Let's discuss this further.

2020-07-31 09:59 UTC, eqfarhad commented on configs/smtp_test_template.yaml
> -to: "yyz@xx.fr"
completely make sense if we just use smtp.yaml for testing purposes as well

2020-07-31 10:23 UTC, eqfarhad commented on pkg/controller/v1alpha/authorityrequest/handler.go
> +		var err error
this err and the next err which you mentioned in the next conversion are the same and we have to do same for both,

btw before any changes we had this line :
```
err := authorityHandler.Init()
if err == nil {
	changeStatus := authorityHandler.Create(authorityRequestCopy)
	if changeStatus {
		t.sendEmail("authority-creation-failure", authorityRequestCopy)
		authorityRequestCopy.Status.State = failure
		authorityRequestCopy.Status.Message = []string{"Authority establishment failed", err.Error()}
		}
	}

```

and it was making sense to have err,
however in the recent structure update, the Init function is not returning any err value to us, and we don't need it as well because in init function we are just syncing the fake clients.
https://github.com/EdgeNet-project/edgenet/blob/1a60d0c79ec170b828b4fcd2e3e494c457ba35cd/pkg/controller/v1alpha/authorityrequest/handler.go#L50

so in my last commit i just removed the var err message + in the status message we can just put the statusDict["authority-failed"].

2020-07-31 18:37 UTC, bsenel approved these changes
We need to look at the unit tests prepared again to make them more concrete. However, I merge the code for you to focus on the other tasks.

Congrats!

2020-07-31 18:37 UTC, merged