Debian support added. Ubuntu support tested.
EdgeNet-project/edgenet-legacy-2024 pull request #135
Opened 2020-08-06 12:56 UTC by habdullah

2020-08-13 17:12 UTC, bsenel requested changes
This is almost ready to merge. And also a friendly reminder, please be sure the commands work smoothly.

2020-08-13 17:12 UTC, bsenel commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +
Let's remove the blank line.

2020-08-13 17:12 UTC, bsenel commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +
Same as above, the blank line.

2020-08-13 17:12 UTC, bsenel commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +			NCCopy.Status.Message = append(NCCopy.Status.Message, statusDict["invalid-host"])
Maybe I couldn't see that but it seems there is no `statusDict` defined. Can you please refer to and point out it?

2020-08-13 17:12 UTC, bsenel commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +				NCCopy.Status.Message = append(NCCopy.Status.Message, statusDict["node-ok"])
Same as above, `statusDict`.

2020-08-13 17:12 UTC, bsenel commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +			NCCopy.Status.Message = append(NCCopy.Status.Message, statusDict["authority-disabled"])
Same as above, `statusDict`.

2020-08-13 17:12 UTC, bsenel commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +			NCCopy.Status.Message = append(NCCopy.Status.Message, statusDict["invalid-host"])
Same as above, `statusDict`.

2020-08-13 17:12 UTC, bsenel commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +
Please remove the blank line.

2020-08-13 20:15 UTC, habdullah commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +	node.Clientset = t.clientset
I don't know where I pulled this from I don't see this in the upstream branch. Deleting

2020-08-13 20:16 UTC, habdullah commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +		recordType := remoteip.GetRecordType(NCCopy.Spec.Host)
Same. Don't see this in the upstream branch. Deleting.

2020-08-13 20:16 UTC, habdullah commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +		recordType := remoteip.GetRecordType(NCCopy.Spec.Host)
Same. Don't see this in the upstream branch. Deleting.

2020-08-13 20:16 UTC, habdullah commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +				node.SetNodeScheduling(nodeName, !NCCopy.Spec.Enabled)
Same. Don't see this in the upstream branch. Deleting.

2020-08-13 20:16 UTC, habdullah commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +	NCCopy *apps_v1alpha.NodeContribution) error {
Same. Don't see this in the upstream branch. Deleting.

2020-08-13 20:16 UTC, habdullah commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +			err := node.SetNodeScheduling(nodeName, !NCCopy.Spec.Enabled)
Same. Don't see this in the upstream branch. Deleting.

2020-08-13 20:16 UTC, habdullah commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +			var ownerReferences []metav1.OwnerReference
Same. Don't see this in the upstream branch. Deleting.

2020-08-14 12:08 UTC, bsenel approved these changes
I am approving the request provided that the code to be tested in the real environment later.

Congrats 👍

2020-08-14 12:08 UTC, merged