Release 1.0 node contribution - More OS support added
EdgeNet-project/edgenet-legacy-2024 pull request #136
Opened 2020-08-14 15:15 UTC by eqfarhad

List of tested and added operating systems:

- CentOS 7
- Red Hat Enterprise Linux (RHEL) 7
- Fedora 25+
- HypriotOS v1.0.1+

- [ ] The ID of real HypriotOS should get check

2020-08-17 12:02 UTC, bsenel commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +			dockerInstallation = []string{""}
Do we have an alternative for `dockerInstallation = []string{""}` like `dockerInstallation = nil` here?

2020-08-17 12:03 UTC, bsenel requested changes
Please just check the issue I pointed out then we can merge this.

2020-08-17 12:29 UTC, eqfarhad commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +			dockerInstallation = []string{""}
okay, i will check it now

2020-08-17 23:40 UTC, eqfarhad commented on pkg/controller/v1alpha/nodecontribution/handler.go
> +			dockerInstallation = []string{""}
I checked and it's working well with nil. so i changed it.

2020-08-19 11:36 UTC, bsenel approved these changes
It is OK now, congrats! 🎉

2020-08-19 11:36 UTC, merged