Release 1.0 selective deployment - Unit test added
EdgeNet-project/edgenet-legacy-2024 pull request #137
Opened 2020-08-17 12:26 UTC by eqfarhad

- Unit test of selective deployment

2020-08-19 12:26 UTC, bsenel requested changes
I've just reviewed roughly and pointed out some issues. Let's try to present profundity in tests here.

2020-08-19 12:26 UTC, bsenel commented on pkg/controller/v1alpha/selectivedeployment/selectivedeployment_test.go
> +	})
You should also check with the node name as you did for the par of Deployment and DaemonSet.

2020-08-19 12:26 UTC, bsenel commented on pkg/controller/v1alpha/selectivedeployment/selectivedeployment_test.go
> +	})
These tests should also include changes in selectors regarding the **quantity, operator, name (type), and values**.

2020-08-19 12:26 UTC, bsenel commented on pkg/controller/v1alpha/selectivedeployment/selectivedeployment_test.go
> +	})
Please provide different quantities in the selectors and take them into account at the tests.

2020-08-19 12:26 UTC, bsenel commented on pkg/controller/v1alpha/selectivedeployment/selectivedeployment_test.go
> +		_, status := g.handler.getByNode(g.nodeUSObj.GetName())
Please also take the owner list into account not only the status.

2020-08-19 12:26 UTC, bsenel commented on pkg/controller/v1alpha/selectivedeployment/selectivedeployment_test.go
> +		_, status := g.handler.getByNode(g.nodeFRObj.GetName())
Please also take the owner list into account not only the status.

2020-08-19 12:26 UTC, bsenel commented on pkg/controller/v1alpha/selectivedeployment/selectivedeployment_test.go
> +		_, status := g.handler.getByNode(g.nodeFRObj.GetName())
Please also take the owner list into account not only the status.

2020-08-19 12:26 UTC, bsenel commented on pkg/controller/v1alpha/selectivedeployment/controller_test.go
> +	g.client.CoreV1().Nodes().Create(g.nodeUSObj.DeepCopy())
You may consider creating more nodes here.

2020-08-19 12:26 UTC, bsenel commented on pkg/controller/v1alpha/selectivedeployment/controller_test.go
> +	g.edgenetclient.AppsV1alpha().SelectiveDeployments("").Update(g.sdObjDeployment.DeepCopy())
Include the Selector of Selective Deployments right here.

2020-08-22 12:41 UTC, bsenel requested changes
It requires minor changes and then that will be ready to go!

2020-08-22 12:41 UTC, bsenel commented on pkg/controller/v1alpha/selectivedeployment/controller_test.go
> +	}
Can you please also include the second deployment as well?

2020-08-24 08:27 UTC, eqfarhad commented on pkg/controller/v1alpha/selectivedeployment/controller_test.go
> +	}
> Can you please also include the second deployment as well?

Can you please explain more?
Because right now in the if state i'm checking both of them, so i couldn't understand what you meant exactly.

(btw i just realized that the t.log() is extra in here and i will delete this line.)

2020-08-24 10:00 UTC, bsenel commented on pkg/controller/v1alpha/selectivedeployment/controller_test.go
> +	}
At line 55, you mention a second deployment but you only check one deployment as of line 65. The second deployment should be included in the testing.

2020-08-24 10:01 UTC, bsenel requested changes
The second deployment in the testing is still ignored. Let's also include that!

2020-08-24 10:38 UTC, eqfarhad commented on pkg/controller/v1alpha/selectivedeployment/controller_test.go
> +	}
okay, i see, i will modify it now

2020-09-01 13:42 UTC, bsenel approved these changes
Good! It seems ready to get merged, congrats!

2020-09-01 13:42 UTC, merged