Updated Nodelabeler Controller to Match with the Sample-Controller
EdgeNet-project/edgenet-legacy-2024 pull request #157
Opened 2021-08-20 07:32 UTC by ubombar

Goal of this patch is to use the best practices in nodelabeler controller. To do this I have utilized [sample-controller](https://github.com/kubernetes/sample-controller/blob/master/controller.go).

Things I have changed:
- Updated the controller structure.
- Removed handler
- Updated main
- Updated test

2021-08-30 12:40 UTC, bsenel requested changes
This is a good first start. 

As we don't use the EdgeNet custom resources, it is not necessary to include the EdgeNet clientset.

Additionally, the unit test is not functional as the lines turned into comment.

Can you please update these parts?

2021-08-30 12:40 UTC, bsenel commented on cmd/nodelabeler/main.go
> +	kubeclientset, err := bootstrap.CreateClientset("kubeconfig")
We use pods to deploy our services. Therefore, it should be serviceaccount instead of kubeconfig.

2021-08-30 12:40 UTC, bsenel commented on cmd/nodelabeler/main.go
> +	}
`edgenetclientset` here is not functional. The question is, is this clientset in use in the controller? If yes, can you please point out the line where we use that?

2021-08-30 12:40 UTC, bsenel commented on cmd/nodelabeler/main.go
> +	edgenetInformerFactory := informers.NewSharedInformerFactory(edgenetclientset, 0)
The same question here applies to `edgenetclientset`.

2021-08-30 12:40 UTC, bsenel commented on cmd/nodelabeler/main.go
> +		edgenetclientset,
Same here `edgenetclientset`.

2021-08-30 12:40 UTC, bsenel commented on cmd/nodelabeler/main.go
> +	edgenetInformerFactory.Start(stopCh)
As `edgenetclientset` is not in use, `edgenetInformerFactory` should be gone.

2021-08-30 12:40 UTC, bsenel commented on pkg/controller/apps/v1/nodelabeler/controller.go
> +	edgenetclientset clientset.Interface
You need to remove this part.

2021-08-30 12:40 UTC, bsenel commented on pkg/controller/apps/v1/nodelabeler/controller.go
> +	edgenetclientset clientset.Interface,
We don't use `edgenetclientset` in nodelabeler.

2021-09-06 08:18 UTC, bsenel requested changes
We are almost there! Could you please look at my comments?

2021-09-06 08:18 UTC, bsenel commented on pkg/controller/apps/v1/nodelabeler/controller.go
> +	utilruntime.Must(edgenetscheme.AddToScheme(edgenetscheme.Scheme))
Why do you use `edgenetscheme` here?

2021-09-06 08:18 UTC, bsenel commented on pkg/controller/apps/v1/nodelabeler/controller.go
> +	recorder := eventBroadcaster.NewRecorder(edgenetscheme.Scheme, corev1.EventSource{Component: controllerAgentName})
The same question above applies to this line.

2021-09-06 08:18 UTC, bsenel commented on pkg/controller/apps/v1/nodelabeler/controller_test.go
> +	kubeclientset.CoreV1().Namespaces().Create(context.TODO(), namespace, metav1.CreateOptions{})
The service of nodelabeler runs at cluster scope, therefore namespace definition is unnecessary. Please correct me if I am wrong.

2021-09-06 08:18 UTC, bsenel commented on pkg/controller/apps/v1/nodelabeler/controller_test.go
> +			// g.handler.SetNodeGeolocation(tc.Node.DeepCopy())
You may consider waiting here a bit to give the nodelabeler controller chance to attach the labels.

2021-09-07 07:44 UTC, bsenel requested changes
Two issues here. The very first one is naming. Please be stick to the naming pattern.

And the second one is at the unit test, you need to wait for a while as the controller needs some time to detect `create event` and attach labels.

2021-09-07 07:44 UTC, bsenel commented on pkg/controller/apps/v1/nodelabeler/controller_test.go
> +	// kubeclientset.CoreV1().Namespaces().Create(context.TODO(), namespace, metav1.CreateOptions{})
Please remove these lines instead of making them comment lines.

2021-09-07 07:44 UTC, bsenel commented on pkg/controller/apps/v1/nodelabeler/controller.go
> +	utilruntime.Must(clientsetscheme.AddToScheme(clientsetscheme.Scheme))
I would like you to stick to the naming pattern. Please use `scheme` instead of `clientsetscheme`.

2021-09-07 07:44 UTC, bsenel commented on pkg/controller/apps/v1/nodelabeler/controller.go
> +	recorder := eventBroadcaster.NewRecorder(clientsetscheme.Scheme, corev1.EventSource{Component: controllerAgentName})
Same as above.

2021-09-07 07:44 UTC, bsenel commented on pkg/controller/apps/v1/nodelabeler/controller.go
> +// The main structure of controllerc
Typo issue.

`controllerc` -> `controller`

2021-09-07 07:44 UTC, bsenel commented on pkg/controller/apps/v1/nodelabeler/controller_test.go
> +
Why don't you wait here, maybe 500 ms, to allow the controller to attach the labels right after the node creation?

2021-09-08 16:37 UTC, ubombar commented
Hi! I had a problem with my go tests when I try to test the controller_test.go. The error was about the database path. However I realized I was running the tests in a different way than in the Makefile. So my CWD was different. This is why I thought time.Sleep() function was creating errors. But now I have fixed it so hopefully This PR is ready to be merged :).

2021-09-13 15:10 UTC, bsenel approved these changes

2021-09-13 15:10 UTC, merged

2021-09-13 15:10 UTC, bsenel commented
This went into the release-1.0 branch. Congrats!