Updated Tenant Controller to Match with the Sample-Controller
EdgeNet-project/edgenet-legacy-2024 pull request #158
Opened 2021-09-27 19:10 UTC by ubombar

2021-09-27 19:17 UTC, ubombar commented
Hello, I am still working on the tenant controller since there are some issues on the other files such as userrequest and tenantrequest. Also I have a minor bug when I run the test case. I will be adding more commits as I resolve the issues.

2021-10-27 12:34 UTC, bsenel requested changes
Good start! 

I found the Selective Deployment term in many places. Would you mind replacing them with Tenant? In addition to this, it would be great to follow the same order for the methods in the controllers. 

I also put some comments for you to look at.

2021-10-27 12:34 UTC, bsenel commented on cmd/tenant/main.go
> +	stopCh := signals.SetupSignalHandler()
You should add `klog.InitFlags(nil)` and `flag.Parse()` according to how to use klog description.

2021-10-27 12:34 UTC, bsenel commented on cmd/tenant/main.go
> +	stopCh := signals.SetupSignalHandler()
Would you please put them above `stopCh := signals.SetupSignalHandler()`?

2021-10-27 12:34 UTC, bsenel commented on pkg/controller/apps/v1/nodelabeler/controller.go
>  }
It seems like the old version of the node labeler controller.

2021-10-27 12:34 UTC, bsenel commented on pkg/controller/apps/v1/nodelabeler/controller_test.go
> -	}()
Previous version?

2021-10-27 12:34 UTC, bsenel commented on pkg/controller/apps/v1/nodelabeler/handler.go
> +}
Yes, not it is clear that the pull request includes the previous version of the node labeler controller.

2021-10-27 12:34 UTC, bsenel commented on pkg/controller/apps/v1/nodelabeler/nodelabeler_test.go
> +	flag.String("geolite-path", "../../../../../assets/database/GeoLite2-City/GeoLite2-City.mmdb", "Set GeoIP DB path.")
Please look at all the files related to node labeler.

2021-10-27 12:34 UTC, bsenel commented on pkg/controller/registration/v1alpha/tenantrequest/handler.go
> +								permission.ConfigureTenantPermissions(tenant, user.DeepCopy(), tenantv1alpha.SetAsOwnerReference(tenant), t.edgenetClientset)
You might consider putting `var EdgenetClientset clientset.Interface` as a global variable into the permission package and sync that in the `NewController` method.

2021-10-27 12:34 UTC, bsenel commented on pkg/controller/registration/v1alpha/userrequest/handler.go
> +				permission.ConfigureTenantPermissions(tenant, userRequest, tenantv1alpha.SetAsOwnerReference(tenant), t.edgenetClientset)
Same as above.

2021-10-27 12:34 UTC, bsenel commented on pkg/permission/permission.go
>  var Clientset kubernetes.Interface
You can define the global variable for the EdgeNet client here.

2021-10-27 12:34 UTC, bsenel commented on pkg/registration/registration.go
> +func CreateTenant(obj interface{}, edgenetclientset clientset.Interface) bool {
Please define the global variable for `edgenetclientset` at line 59.

2021-10-27 12:34 UTC, bsenel commented on pkg/controller/core/v1alpha/tenant/controller.go
>  // Constant variables for events
I prefer moving this part, until line 94, to above the Controller struct type.

2021-10-27 12:34 UTC, bsenel commented on pkg/controller/core/v1alpha/tenant/controller.go
> +		DeleteFunc: controller.handleObject,
Please use `enqueueTenant` to replace `handleObject` here.

2021-10-27 12:34 UTC, bsenel commented on pkg/controller/core/v1alpha/tenant/controller.go
> +	klog.V(4).Infoln("Starting Selective Deployment controller")
I see that the Selective Deployment term exists in so many places.

2021-10-27 12:34 UTC, bsenel commented on pkg/controller/core/v1alpha/tenant/controller.go
> +	event, shutdown := c.workqueue.Get()
Please replace `event, shutdown` with `obj, shutdown`.

2021-10-27 12:34 UTC, bsenel commented on pkg/controller/core/v1alpha/tenant/controller.go
> +		utilruntime.HandleError(fmt.Errorf("tenant '%s' in work queue no longer exists", name))
It should be above line 273.

2021-10-27 12:34 UTC, bsenel commented on pkg/controller/core/v1alpha/tenant/controller.go
> +		return nil
return err.

2021-10-27 12:34 UTC, bsenel commented on pkg/controller/core/v1alpha/tenant/controller.go
> +	c.ObjectCreatedOrUpdated(tenant)
Let's find a proper name for this method. `TuneTenant()`?

2021-12-09 16:12 UTC, bsenel approved these changes
It seems OK now, so it goes into release-1.0.

2021-12-09 16:12 UTC, merged