Documentation Fixes and Additions
EdgeNet-project/edgenet-legacy-2024 pull request #173
Opened 2022-11-16 22:58 UTC by ubombar

This patch contains some adding and fixes in the documentation part. I am looking forward for your feedback.

2022-11-17 15:12 UTC, bsenel requested changes
Thank you for your effort! It seems in good shape, but it requires more work to be ready.

Can you please address my comments?

2022-11-17 15:12 UTC, bsenel commented on docs/README.md
> +EdgeNet, the open-source globally distributed edge cloud for Internet researchers, is based on industry-standard Cloud software, using [Docker](https://www.docker.com/) for containerization and [Kube
Can you please rewrite this part?

2022-11-17 15:12 UTC, bsenel commented on docs/README.md
> +EdgeNet, the open-source globally distributed edge cloud for Internet researchers, is based on industry-standard Cloud software, using [Docker](https://www.docker.com/) for containerization and [Kube
Here, as this doc is on GitHub, we may introduce the source code first, then mention that we provide researchers a testbed for the not-for-profit research.

2022-11-17 15:12 UTC, bsenel commented on docs/README.md
> +Additionally, we provide a testbed for all researchers. To open an account please refer to the [Registering a tenant into EdgeNet](tenant_registration.md). For getting more info about the project vis
I would not mention opening an account here as you introduce components below. It is better to directly take those who want to register a tenant with the EdgeNet testbed to the testbed website.

2022-11-17 15:12 UTC, bsenel commented on docs/README.md
> +* [VPN Peer](custom_resources.md#vpn-peer)
Can we introduce categories here?

Like below:
1) Multitenancy
- Tenant
- Tenant Resource Quota
- Subnamespace
- Slice
- Slice Claim
- Tenant Request
- Role Request
- Cluster Role Request

2) Multi-provider
- Node Contribution
- VPN Peer

3) Location-based node selection
- Selective Deployment

2022-11-17 15:12 UTC, bsenel commented on docs/README.md
> +EdgeNet, the open-source globally distributed edge cloud for Internet researchers, is based on industry-standard Cloud software, using [Docker](https://www.docker.com/) for containerization and [Kube
We should separate these two here clearly; the EdgeNet source code and the EdgeNet testbed. Then the rest of doc should be only about the source code.

2022-11-17 15:12 UTC, bsenel commented on docs/cluster_creation.md
> +# Cluster creation from EdgeNet source code
I would express it like **Deploying EdgeNet on a Kubernetes cluster**.

2022-11-17 15:12 UTC, bsenel commented on docs/cluster_creation.md
> +You will need a Kubernetes cluster to extend it to support EdgeNet. There are many ways to setup a Kubernetes cluster all of which require different knowledge. You can refer [here](https://kubernetes
This should be in another section that is about how to create a cluster.

2022-11-17 15:12 UTC, bsenel commented on docs/cluster_creation.md
> +Before the tutorial, it is assumed you have an access to a working Kubernetes cluster with a valid kubeconfig and `kubectl` command-line tool installed.
This should go into the section of **Technologies you will use**.

2022-11-17 15:12 UTC, bsenel commented on docs/cluster_creation.md
> +There are two stages for installing EdgeNet to a Kubernetes cluster. First, it is necessary to install the [CRDs](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/
Please rewrite this part.

2022-11-17 15:12 UTC, bsenel commented on docs/cluster_creation.md
> +<!-- *TODO: How to compile EdgeNet from source?* -->
Can you please provide subsections for each [deployment file](https://github.com/EdgeNet-project/edgenet/tree/main/build/yamls/kubernetes)?

2022-11-17 15:12 UTC, bsenel commented on docs/custom_resources.md
> +EdgeNet is a distributed edge cluster that has nodes all around the world. To connect these nodes in the same network a VPN is used. VPN peer objects contain information about different nodes IP addr
Can you please put them in categories, as I mentioned in one of the previous comments?

2022-11-17 15:12 UTC, bsenel commented on docs/custom_resources.md
> +EdgeNet is a distributed edge cluster that has nodes all around the world. To connect these nodes in the same network a VPN is used. VPN peer objects contain information about different nodes IP addr
We need to revisit the descriptions too.

2022-11-21 21:50 UTC, ubombar commented on docs/custom_resources.md
> +EdgeNet is a distributed edge cluster that has nodes all around the world. To connect these nodes in the same network a VPN is used. VPN peer objects contain information about different nodes IP addr
Hello, I have rearranged the content on this page and rephrased some of the descriptions. How is it now?

2022-11-21 22:30 UTC, ubombar commented on docs/cluster_creation.md
> +<!-- *TODO: How to compile EdgeNet from source?* -->
I have written the section for one of the yamls. If its adequate I can do it for the others as well.

2023-07-06 08:11 UTC, ubombar commented
As I mentioned in the #180 I will also add the fedmanctl documentation, tutorial, and installation guide to this patch.

2023-07-17 11:05 UTC, ubombar commented
I have also added the fedmanctl documentation with this PR.

2023-07-21 15:00 UTC, ubombar commented
I added the latest updates on the `fedmanctl` to the documentation.

2023-07-21 15:02 UTC, merged